SELECT * FROM TIPO_ARTICULO;
INSERT INTO TIPO_ARTICULO VALUES ('TA03','OTROS');

SELECT * FROM ARTICULO;
SELECT DESCRIPCION FROM ARTICULO;
INSERT INTO ARTICULO VALUES ('AMA10000007','CINTA MASTIC','TA01');

SELECT * FROM Persona;
SELECT * FROM Persona WHERE DNI LIKE '%7%';
INSERT INTO Persona VALUES ('44182117','Joshua','Ormachea','Del Aguila','2017-12-29');