SELECT * FROM TIPO_ARTICULO;
INSERT INTO TIPO_ARTICULO VALUES ('TA03','OTROS');

SELECT * FROM ARTICULO;
SELECT Cantidad FROM ARTICULO WHERE Descripcion='Cemento';
SELECT DESCRIPCION FROM ARTICULO WHERE CANTIDAD >0;
SELECT Codigo FROM articulo WHERE Descripcion='cemento';
INSERT INTO ARTICULO VALUES ('AMA10000007','CINTA MASTIC','TA01');

SELECT * FROM Persona;
SELECT * FROM Persona WHERE DNI LIKE '%7%';
SELECT * FROM Persona P LEFT JOIN Trabajador T ON P.`DNI`=T.`DNI` WHERE T.`CODIGO`IS NULL;
INSERT INTO Persona VALUES ('44182117','Joshua','Ormachea','Del Aguila','2017-12-29');

SELECT * FROM Trabajador;
SELECT T.Correo FROM Trabajador T INNER JOIN Persona P ON T.`DNI`=P.`DNI`WHERE CONCAT(P.`APELLIDOP`, ' ',P.`APELLIDOM`, ' ',P.`NOMBRES`)='Ormachea Del Aguila Joshua';
SELECT MAX(Codigo) FROM Trabajador;
SELECT P.`APELLIDOP`, P.`APELLIDOM`, P.`NOMBRES` FROM Trabajador T INNER JOIN Persona P ON T.`DNI`=P.`DNI` WHERE CONCAT(P.`APELLIDOP`, ' ',P.`APELLIDOM`, ' ',P.`NOMBRES`)<>'Coronado Silupu Cesar' ORDER BY P.`APELLIDOP`;
SELECT T.`CODIGO`, T.`DNI`, P.`NOMBRES`, P.`APELLIDOP`, P.`APELLIDOM`, A.`AREA`, Pu.`PUESTO` FROM Trabajador T INNER JOIN Persona P ON T.`DNI`=P.`DNI` INNER JOIN AREA A ON T.`IDAREA`=A.`ID` INNER JOIN Puesto Pu ON T.`IDPUESTO`=Pu.`ID`;
SELECT A.`AREA` FROM Trabajador T INNER JOIN Persona P ON T.`DNI`=P.`DNI` INNER JOIN AREA A ON T.`IDAREA`=A.`ID` WHERE CONCAT(P.`APELLIDOP`, ' ', P.`APELLIDOM`, ' ', P.`NOMBRES`)='Ormachea Del Aguila Joshua';
INSERT INTO Trabajador VALUES ('8002','46642210',(SELECT Id FROM AREA WHERE AREA='MEDIA TENSION'),(SELECT Id FROM Puesto WHERE Puesto='Tecnico Electricista'));

SELECT * FROM AREA;
SELECT AREA FROM AREA;
SELECT MAX(Id) FROM AREA;
SELECT Id FROM AREA WHERE AREA='ALUMBRADO PUBLICO';
INSERT INTO AREA VALUES ('108','SEGURIDAD');

SELECT * FROM Puesto;

SELECT * FROM NOTA_SALIDA;
SELECT * FROM NOTA_SALIDA WHERE Codigo='17111717530';
INSERT INTO Nota_salida VALUES ('171117102923','8001','8101','2017-11-17','','','');
