SELECT * FROM TIPO_ARTICULO;

INSERT INTO TIPO_ARTICULO VALUES ('TA03','OTROS');

SELECT * FROM ARTICULO;
SELECT DESCRIPCION FROM ARTICULO;

INSERT INTO ARTICULO VALUES ('AMA10000007','CINTA MASTIC','TA01');